import type { GeneratePocAssetsPayload, GeneratePocAssetsResult, GeneratedPocAsset } from "../shared/api";

type NormalizedPocAssetConfig = Required<GeneratePocAssetsPayload>;

const oracleIdentifierPattern = /^[A-Za-z][A-Za-z0-9_$#]*$/;

function normalize(value: string | undefined, fallback: string): string {
  const trimmed = value?.trim();
  return trimmed ? trimmed : fallback;
}

function normalizeOracleIdentifier(value: string | undefined, fallback: string): string {
  const normalized = normalize(value, fallback).replace(/[^A-Za-z0-9_$#]/g, "_").toUpperCase();
  return oracleIdentifierPattern.test(normalized) ? normalized : fallback;
}

function normalizeConfig(payload: GeneratePocAssetsPayload): NormalizedPocAssetConfig {
  return {
    workspaceName: normalize(payload.workspaceName, "AI Launchpad PoC"),
    playbookTitle: normalize(payload.playbookTitle, "RAG Chatbot on Oracle AI Database 26ai"),
    useCase: normalize(payload.useCase, "Oracle AI Vector Search PoC"),
    dbSchema: normalizeOracleIdentifier(payload.dbSchema, "AI_LAUNCHPAD"),
    vectorTable: normalizeOracleIdentifier(payload.vectorTable, "AI_LAUNCHPAD_CHUNKS"),
    objectStorageNamespace: normalize(payload.objectStorageNamespace, "<object-storage-namespace>"),
    objectStorageBucket: normalize(payload.objectStorageBucket, "<object-storage-bucket>"),
    ociRegion: normalize(payload.ociRegion, "ap-tokyo-1"),
    embeddingModel: normalize(payload.embeddingModel, "cohere.embed-multilingual-v3.0")
  };
}

function createWarnings(config: NormalizedPocAssetConfig): string[] {
  const warnings = [
    "生成した asset は template です。実 OCI API、DB 接続、Terraform apply は実行していません。",
    "顧客データ、password、wallet、private key は template に含めないでください。"
  ];

  if (config.objectStorageNamespace.startsWith("<") || config.objectStorageBucket.startsWith("<")) {
    warnings.push("Object Storage namespace / bucket は placeholder です。実行前に環境固有の値へ置き換えてください。");
  }

  return warnings;
}

function createReadme(config: NormalizedPocAssetConfig): string {
  return [
    `# ${config.workspaceName}`,
    "",
    `## Use case`,
    "",
    config.useCase,
    "",
    `## Playbook`,
    "",
    config.playbookTitle,
    "",
    "## Assets",
    "",
    "- `sql/setup_vector_search.sql`: AI Vector Search table と sample query の SQL template",
    "- `python/ingest_documents.py`: Object Storage から文書を読み込む Python skeleton",
    "- `terraform/object_storage.tf`: PoC 用 Object Storage bucket の Terraform skeleton",
    "- `checklist.md`: PoC 実行前の readiness と validation checklist",
    "",
    "## Safety",
    "",
    "- OCI private key、ADB wallet、password、顧客データはこの package に含めない",
    "- SQL / Python / Terraform は実行前に tenancy、compartment、IAM policy、network を確認する",
    "- 生成物は PoC starter であり、本番運用 template ではない"
  ].join("\n");
}

function createSql(config: NormalizedPocAssetConfig): string {
  return [
    `-- ${config.useCase}`,
    `-- Schema: ${config.dbSchema}`,
    "-- 実行前に DB version、VECTOR support、DBMS_CLOUD 権限を確認してください。",
    "",
    `CREATE TABLE ${config.dbSchema}.${config.vectorTable} (`,
    "  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
    "  TITLE VARCHAR2(4000),",
    "  SOURCE_URL VARCHAR2(4000),",
    "  CHUNK_TEXT CLOB,",
    "  VECTOR_EMBEDDING VECTOR",
    ");",
    "",
    `-- Embedding model: ${config.embeddingModel}`,
    `-- SELECT ID, TITLE, VECTOR_DISTANCE(VECTOR_EMBEDDING, :query_embedding, COSINE) AS DISTANCE`,
    `-- FROM ${config.dbSchema}.${config.vectorTable}`,
    "-- ORDER BY DISTANCE",
    "-- FETCH FIRST 5 ROWS ONLY;"
  ].join("\n");
}

function createPython(config: NormalizedPocAssetConfig): string {
  return [
    '"""Document ingestion skeleton for AI Launchpad PoC.',
    "",
    "This file intentionally avoids embedding credentials. Use OCI config,",
    "instance principals, resource principals, or a controlled secret store.",
    '"""',
    "",
    "from __future__ import annotations",
    "",
    "OBJECT_STORAGE_NAMESPACE = " + JSON.stringify(config.objectStorageNamespace),
    "OBJECT_STORAGE_BUCKET = " + JSON.stringify(config.objectStorageBucket),
    "OCI_REGION = " + JSON.stringify(config.ociRegion),
    "VECTOR_TABLE = " + JSON.stringify(`${config.dbSchema}.${config.vectorTable}`),
    "",
    "",
    "def main() -> None:",
    '    print("Prepare Object Storage download, chunking, embedding, and DB insert steps.")',
    '    print(f"Bucket: {OBJECT_STORAGE_NAMESPACE}/{OBJECT_STORAGE_BUCKET} in {OCI_REGION}")',
    '    print(f"Target table: {VECTOR_TABLE}")',
    "",
    "",
    'if __name__ == "__main__":',
    "    main()"
  ].join("\n");
}

function createTerraform(config: NormalizedPocAssetConfig): string {
  return [
    `# ${config.useCase}`,
    "# Terraform skeleton only. Review compartment_id and IAM policy before apply.",
    "",
    'variable "compartment_id" {',
    "  type = string",
    "}",
    "",
    'variable "bucket_name" {',
    "  type    = string",
    `  default = "${config.objectStorageBucket}"`,
    "}",
    "",
    'resource "oci_objectstorage_bucket" "poc_bucket" {',
    "  compartment_id = var.compartment_id",
    `  namespace      = "${config.objectStorageNamespace}"`,
    "  name           = var.bucket_name",
    '  access_type    = "NoPublicAccess"',
    "}"
  ].join("\n");
}

function createChecklist(config: NormalizedPocAssetConfig): string {
  return [
    `# ${config.workspaceName} PoC Checklist`,
    "",
    `## Scope`,
    "",
    `- Playbook: ${config.playbookTitle}`,
    `- Use case: ${config.useCase}`,
    `- Target table: ${config.dbSchema}.${config.vectorTable}`,
    `- Object Storage: ${config.objectStorageNamespace}/${config.objectStorageBucket}`,
    "",
    "## Readiness",
    "",
    "- [ ] OCI config profile と compartment を確認する",
    "- [ ] ADB wallet、network、DB user 権限を確認する",
    "- [ ] Object Storage bucket と IAM policy を確認する",
    "- [ ] 顧客データ、secret、private key を package に含めていないことを確認する",
    "",
    "## Demo validation",
    "",
    "- [ ] SQL table と VECTOR column の作成手順をレビューする",
    "- [ ] document chunking と embedding model の前提を説明できる",
    "- [ ] similarity query の結果と引用 source を確認する",
    "- [ ] PoC 後の follow-up action と owner を整理する"
  ].join("\n");
}

function createAsset(kind: GeneratedPocAsset["kind"], fileName: string, title: string, content: string): GeneratedPocAsset {
  return {
    kind,
    fileName,
    title,
    content
  };
}

export function generatePocAssets(payload: GeneratePocAssetsPayload = {}): GeneratePocAssetsResult {
  const config = normalizeConfig(payload);
  return {
    status: "generated",
    message: "PoC asset templates を生成しました。実行や外部接続は行っていません。",
    generatedAt: new Date().toISOString(),
    warnings: createWarnings(config),
    assets: [
      createAsset("readme", "README.md", "PoC README", createReadme(config)),
      createAsset("sql", "sql/setup_vector_search.sql", "AI Vector Search SQL", createSql(config)),
      createAsset("python", "python/ingest_documents.py", "Document ingestion Python", createPython(config)),
      createAsset("terraform", "terraform/object_storage.tf", "Object Storage Terraform", createTerraform(config)),
      createAsset("checklist", "checklist.md", "PoC validation checklist", createChecklist(config))
    ]
  };
}
