export type OracleVectorSearchConfig = {
  connectionName?: string;
  tableName?: string;
  vectorColumn?: string;
  textColumn?: string;
  embeddingModel?: string;
  topK?: number;
  configured: boolean;
};

export type OracleVectorSearchExecutionStatus =
  | "not_configured"
  | "invalid_config"
  | "dry_run"
  | "executed"
  | "unavailable";

export type OracleVectorSearchRow = {
  chunkText: string;
  distance?: number;
  id?: string;
  title?: string;
  sourceUrl?: string;
};

export type OracleVectorSearchBindVariable = {
  name: string;
  purpose: string;
};

export type OracleVectorSearchPlan = {
  connectionName: string;
  tableName: string;
  vectorColumn: string;
  textColumn: string;
  embeddingModel: string;
  topK: number;
  sqlPreview: string;
  sqlclScriptPreview: string;
  bindVariables: OracleVectorSearchBindVariable[];
};

export type OracleVectorSearchReadinessCheck = {
  name: string;
  status: "ready" | "not-configured" | "invalid" | "unavailable";
  message: string;
  path?: string;
  checks?: Array<{
    name: string;
    ok: boolean;
    message: string;
  }>;
};

export type OracleVectorSearchExecutionPayload = {
  question: string;
  config?: Partial<OracleVectorSearchConfig>;
  maxResults?: number;
};

export type OracleVectorSearchExecutionResult = {
  status: OracleVectorSearchExecutionStatus;
  message: string;
  plan?: OracleVectorSearchPlan;
  rows?: OracleVectorSearchRow[];
  readinessChecks?: OracleVectorSearchReadinessCheck[];
  validationErrors?: string[];
  latencyMs: number;
  executedAt: string;
};

export const defaultOracleVectorSearchConfig: OracleVectorSearchConfig = {
  connectionName: "",
  tableName: "",
  vectorColumn: "VECTOR_EMBEDDING",
  textColumn: "CHUNK_TEXT",
  embeddingModel: "",
  topK: 3,
  configured: false
};

const simpleOracleIdentifierPattern = /^[A-Za-z][A-Za-z0-9_$#]*$/;
const sqlclConnectionAliasPattern = /^[A-Za-z][A-Za-z0-9_.-]*$/;

const requiredConfigFields: Array<{
  key: keyof Pick<OracleVectorSearchConfig, "connectionName" | "tableName" | "vectorColumn" | "textColumn" | "embeddingModel">;
  label: string;
}> = [
  { key: "connectionName", label: "connection" },
  { key: "tableName", label: "table" },
  { key: "vectorColumn", label: "vector column" },
  { key: "textColumn", label: "text column" },
  { key: "embeddingModel", label: "embedding model" }
];

function normalizeConfigString(value: string | undefined): string {
  return value?.trim() ?? "";
}

function normalizeTopK(value: number | undefined): number {
  const requestedTopK = Number(value ?? defaultOracleVectorSearchConfig.topK);
  const integerTopK = Number.isFinite(requestedTopK)
    ? Math.trunc(requestedTopK)
    : (defaultOracleVectorSearchConfig.topK ?? 3);
  return Math.max(1, Math.min(integerTopK, 20));
}

function isOracleIdentifierPath(value: string): boolean {
  return value.split(".").every((part) => simpleOracleIdentifierPattern.test(part));
}

function createConfigValidationErrors(config: OracleVectorSearchConfig): string[] {
  const identifiers = [
    { label: "table", value: config.tableName ?? "" },
    { label: "vector column", value: config.vectorColumn ?? "" },
    { label: "text column", value: config.textColumn ?? "" }
  ];

  const connectionErrors = sqlclConnectionAliasPattern.test(config.connectionName ?? "")
    ? []
    : [
        "connection は SQLcl connection alias として英数字、_、-、. のみで指定してください。credential、connect descriptor、改行は含めないでください。"
      ];
  const identifierErrors = identifiers.flatMap(({ label, value }) =>
    isOracleIdentifierPath(value)
      ? []
      : [`${label} は schema.table または column 形式の Oracle identifier として指定してください。`]
  );

  return [...connectionErrors, ...identifierErrors];
}

function normalizeSqlclTextLiteral(value: string): string {
  return value.replace(/\s+/g, " ").trim().replace(/'/g, "''");
}

function normalizeSqlclCommentValue(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function createSqlclScriptPreview(question: string, config: OracleVectorSearchConfig, sqlPreview: string): string {
  const queryText = normalizeSqlclTextLiteral(question) || "default knowledge question";
  const connectionName = normalizeSqlclCommentValue(config.connectionName ?? "");
  const embeddingModel = normalizeSqlclCommentValue(config.embeddingModel ?? "");

  return [
    "SET DEFINE OFF",
    "SET PAGESIZE 100",
    "SET LINESIZE 200",
    "",
    "-- Oracle Vector Search dry-run execution contract",
    `-- Connection: ${connectionName}`,
    `-- Embedding model: ${embeddingModel}`,
    "-- Generate :query_embedding from :query_text before running the SELECT.",
    "",
    "VAR query_text CLOB",
    `EXEC :query_text := '${queryText}';`,
    "",
    "-- Bind :query_embedding as VECTOR generated by the configured embedding model.",
    `${sqlPreview};`
  ].join("\n");
}

export function getMissingOracleVectorSearchConfigFields(config: OracleVectorSearchConfig): string[] {
  return requiredConfigFields.flatMap(({ key, label }) => (normalizeConfigString(config[key]) ? [] : [label]));
}

export function isOracleVectorSearchConfigured(config: OracleVectorSearchConfig): boolean {
  return getMissingOracleVectorSearchConfigFields(config).length === 0;
}

export function normalizeOracleVectorSearchConfig(
  config: Partial<OracleVectorSearchConfig> = {}
): OracleVectorSearchConfig {
  const normalized = {
    ...defaultOracleVectorSearchConfig,
    ...config,
    connectionName: normalizeConfigString(config.connectionName ?? defaultOracleVectorSearchConfig.connectionName),
    tableName: normalizeConfigString(config.tableName ?? defaultOracleVectorSearchConfig.tableName),
    vectorColumn: normalizeConfigString(config.vectorColumn ?? defaultOracleVectorSearchConfig.vectorColumn),
    textColumn: normalizeConfigString(config.textColumn ?? defaultOracleVectorSearchConfig.textColumn),
    embeddingModel: normalizeConfigString(config.embeddingModel ?? defaultOracleVectorSearchConfig.embeddingModel),
    topK: normalizeTopK(config.topK)
  };

  return {
    ...normalized,
    configured: isOracleVectorSearchConfigured(normalized)
  };
}

export function createOracleVectorSearchPlan(
  question: string,
  config: Partial<OracleVectorSearchConfig> = {},
  maxResults?: number
): { ok: true; plan: OracleVectorSearchPlan } | { ok: false; status: "not_configured" | "invalid_config"; errors: string[] } {
  const normalizedConfig = normalizeOracleVectorSearchConfig({
    ...config,
    topK: maxResults ?? config.topK
  });
  const missingFields = getMissingOracleVectorSearchConfigFields(normalizedConfig);

  if (missingFields.length > 0) {
    return {
      ok: false,
      status: "not_configured",
      errors: [`Oracle Vector Search config に不足があります: ${missingFields.join(", ")}`]
    };
  }

  const validationErrors = createConfigValidationErrors(normalizedConfig);
  if (validationErrors.length > 0) {
    return {
      ok: false,
      status: "invalid_config",
      errors: validationErrors
    };
  }

  const topK = normalizedConfig.topK ?? defaultOracleVectorSearchConfig.topK ?? 3;
  const sqlPreview = [
    "SELECT",
    "  ID,",
    "  TITLE,",
    "  SOURCE_URL,",
    `  ${normalizedConfig.textColumn} AS CHUNK_TEXT,`,
    `  VECTOR_DISTANCE(${normalizedConfig.vectorColumn}, :query_embedding, COSINE) AS DISTANCE`,
    `FROM ${normalizedConfig.tableName}`,
    "ORDER BY DISTANCE",
    `FETCH FIRST ${topK} ROWS ONLY`
  ].join("\n");
  const sqlclScriptPreview = createSqlclScriptPreview(question, normalizedConfig, sqlPreview);

  return {
    ok: true,
    plan: {
      connectionName: normalizedConfig.connectionName ?? "",
      tableName: normalizedConfig.tableName ?? "",
      vectorColumn: normalizedConfig.vectorColumn ?? "",
      textColumn: normalizedConfig.textColumn ?? "",
      embeddingModel: normalizedConfig.embeddingModel ?? "",
      topK,
      sqlPreview,
      sqlclScriptPreview,
      bindVariables: [
        {
          name: "query_text",
          purpose: `Embedding input text: ${question.trim() || "default knowledge question"}`
        },
        {
          name: "query_embedding",
          purpose: `Vector generated by ${normalizedConfig.embeddingModel}`
        }
      ]
    }
  };
}

export function executeOracleVectorSearchDryRun(payload: OracleVectorSearchExecutionPayload): OracleVectorSearchExecutionResult {
  const startedAt = Date.now();
  const planResult = createOracleVectorSearchPlan(payload.question, payload.config, payload.maxResults);

  if (!planResult.ok) {
    return {
      status: planResult.status,
      message:
        planResult.status === "not_configured"
          ? "Oracle Vector Search の実行に必要な設定が不足しています。"
          : "Oracle Vector Search の設定に安全でない identifier が含まれています。",
      validationErrors: planResult.errors,
      latencyMs: Date.now() - startedAt,
      executedAt: new Date().toISOString()
    };
  }

  return {
    status: "dry_run",
    message: "Oracle Vector Search の実行契約を dry-run しました。実 DB 呼び出しはまだ実行していません。",
    plan: planResult.plan,
    latencyMs: Date.now() - startedAt,
    executedAt: new Date().toISOString()
  };
}
