import * as assert from "node:assert/strict";
import { test } from "node:test";
import { createKnowledgeAnswerFileName, formatKnowledgeAnswerMarkdown } from "./knowledgeAnswerExport";

test("createKnowledgeAnswerFileName sanitizes unsafe filename characters", () => {
  assert.equal(
    createKnowledgeAnswerFileName('金融 PoC: RAG / "Demo"', "2026-05-26T10:20:30.000Z"),
    "金融-PoC-RAG-Demo-grounded-answer-2026-05-26.md"
  );
});

test("formatKnowledgeAnswerMarkdown includes answer sources and Oracle Vector plan", () => {
  const markdown = formatKnowledgeAnswerMarkdown({
    workspaceName: "金融向け RAG 提案",
    playbookTitle: "RAG Chatbot on Oracle AI Database 26ai",
    question: "PoC の前提は?",
    answer: "ADB、Object Storage、embedding model の確認が必要です。",
    adapterStatus: "Adapter: oracle-vector-search / dry_run",
    sources: [
      {
        chunk: {
          id: "chunk-1",
          captureId: "capture-1",
          title: "Oracle AI Vector Search",
          sourceUrl: "https://docs.oracle.com/vector-search",
          sourceKind: "page",
          text: "Vector Search setup"
        },
        score: 4,
        matchedTerms: ["vector", "search"],
        excerpt: "Vector Search setup"
      }
    ],
    oracleVectorExecution: {
      status: "dry_run",
      message: "Oracle Vector Search の実行契約を dry-run しました。",
      latencyMs: 12,
      executedAt: "2026-05-26T10:20:30.000Z",
      plan: {
        connectionName: "adb-sales-demo",
        tableName: "SALES_AI.CUSTOMER_CHUNKS",
        vectorColumn: "VECTOR_EMBEDDING",
        textColumn: "CHUNK_TEXT",
        embeddingModel: "cohere.embed-multilingual-v3.0",
        topK: 3,
        sqlPreview: "SELECT *\nFROM SALES_AI.CUSTOMER_CHUNKS",
        bindVariables: [
          {
            name: "query_embedding",
            purpose: "Vector generated by cohere.embed-multilingual-v3.0"
          }
        ]
      }
    }
  });

  assert.match(markdown, /# 金融向け RAG 提案 Grounded Answer/);
  assert.match(markdown, /PoC の前提は\?/);
  assert.match(markdown, /Oracle AI Vector Search/);
  assert.match(markdown, /https:\/\/docs\.oracle\.com\/vector-search/);
  assert.match(markdown, /```sql\nSELECT \*\nFROM SALES_AI\.CUSTOMER_CHUNKS\n```/);
  assert.match(markdown, /`query_embedding`/);
});
