import * as assert from "node:assert/strict";
import { test } from "node:test";
import {
  createKnowledgeAnswerFileName,
  createOracleVectorSqlFileName,
  formatKnowledgeAnswerMarkdown
} from "./knowledgeAnswerExport";

test("createKnowledgeAnswerFileName sanitizes unsafe filename characters", () => {
  assert.equal(
    createKnowledgeAnswerFileName('金融 PoC: RAG / "Demo"', "2026-05-26T10:20:30.000Z"),
    "金融-PoC-RAG-Demo-grounded-answer-2026-05-26.md"
  );
});

test("createOracleVectorSqlFileName creates a SQL download filename", () => {
  assert.equal(
    createOracleVectorSqlFileName("金融 PoC: RAG", "2026-05-26T10:20:30.000Z"),
    "金融-PoC-RAG-oracle-vector-plan-2026-05-26.sql"
  );
});

test("formatKnowledgeAnswerMarkdown includes answer sources and Oracle Vector plan", () => {
  const markdown = formatKnowledgeAnswerMarkdown({
    workspaceName: "金融向け RAG 提案",
    playbookTitle: "RAG Chatbot on Oracle AI Database 26ai",
    question: "PoC の前提は?",
    answer: "ADB、Object Storage、embedding model の確認が必要です。",
    adapterStatus: "Adapter: oracle-vector-search / dry_run",
    sources: [
      {
        chunk: {
          id: "chunk-1",
          captureId: "capture-1",
          title: "Oracle AI Vector Search",
          sourceUrl: "https://docs.oracle.com/vector-search",
          sourceKind: "page",
          text: "Vector Search setup"
        },
        score: 4,
        matchedTerms: ["vector", "search"],
        excerpt: "Vector Search setup"
      }
    ],
    oracleVectorExecution: {
      status: "dry_run",
      message: "Oracle Vector Search の実行契約を dry-run しました。",
      latencyMs: 12,
      executedAt: "2026-05-26T10:20:30.000Z",
      readinessChecks: [
        {
          name: "OCI config",
          status: "ready",
          message: "OCI config と key_file を確認しました。",
          path: "C:\\Users\\demo\\.oci\\config",
          checks: [
            {
              name: "profile",
              ok: true,
              message: "profile [DEFAULT] を確認しました。"
            }
          ]
        },
        {
          name: "SQLcl",
          status: "ready",
          message: "SQLcl executable を確認しました。",
          path: "C:\\oracle\\sqlcl\\bin\\sql.exe",
          checks: [
            {
              name: "sqlcl_path",
              ok: true,
              message: "SQLCL_PATH の executable は読み取り可能です。"
            }
          ]
        },
        {
          name: "ADB wallet",
          status: "not-configured",
          message: "ADB wallet path が未設定です。",
          checks: [
            {
              name: "wallet_path",
              ok: false,
              message: "ADB wallet path が設定されていません。"
            }
          ]
        }
      ],
      plan: {
        connectionName: "adb-sales-demo",
        tableName: "SALES_AI.CUSTOMER_CHUNKS",
        vectorColumn: "VECTOR_EMBEDDING",
        textColumn: "CHUNK_TEXT",
        embeddingModel: "cohere.embed-multilingual-v3.0",
        topK: 3,
        sqlPreview: "SELECT *\nFROM SALES_AI.CUSTOMER_CHUNKS",
        sqlclScriptPreview: "VAR query_text CLOB\nEXEC :query_text := 'PoC の前提は?';\nSELECT *\nFROM SALES_AI.CUSTOMER_CHUNKS;",
        bindVariables: [
          {
            name: "query_embedding",
            purpose: "Vector generated by cohere.embed-multilingual-v3.0"
          }
        ]
      }
    }
  });

  assert.match(markdown, /# 金融向け RAG 提案 Grounded Answer/);
  assert.match(markdown, /PoC の前提は\?/);
  assert.match(markdown, /Oracle AI Vector Search/);
  assert.match(markdown, /https:\/\/docs\.oracle\.com\/vector-search/);
  assert.match(markdown, /### Execution readiness/);
  assert.match(markdown, /OCI config: ready - OCI config と key_file を確認しました。/);
  assert.match(markdown, /ok profile: profile \[DEFAULT\] を確認しました。/);
  assert.match(markdown, /SQLcl: ready - SQLcl executable を確認しました。/);
  assert.match(markdown, /ok sqlcl_path: SQLCL_PATH の executable は読み取り可能です。/);
  assert.match(markdown, /ADB wallet: not-configured - ADB wallet path が未設定です。/);
  assert.match(markdown, /ng wallet_path: ADB wallet path が設定されていません。/);
  assert.match(markdown, /```sql\nSELECT \*\nFROM SALES_AI\.CUSTOMER_CHUNKS\n```/);
  assert.match(markdown, /### SQLcl script preview/);
  assert.match(markdown, /VAR query_text CLOB/);
  assert.match(markdown, /`query_embedding`/);
});
